### ISSUE TITLE
关于数据集的制作

### ISSUE THREAD

**Issue by wxslby** [learner-lu/image-super-resolution#1]
您好，如果我想使用自己的数据集进行训练，请问要如何做？

**Comment by luzhixing12345** [comment]
我研究一下，尽快给你答复

**Comment by Kerri-lovely** [comment]
您好，感谢您的回复！我的qq是1432670918，不知道您是否方便添加好友？感谢您的帮助！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "learner-lu/image-super-resolution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [learner-lu/image-super-resolution] 关于数据集的制作 (Issue #1)





 
我研究一下，尽快给你答复
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luzhixing12345** [comment]
额我搜不到啊，你加我吧，1269185526



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月14日 12:45 |
| 收件人 | ***@***.***> |
| 抄送至 | Lu ***@***.******@***.***> |
| 主题 | Re: [learner-lu/image-super-resolution] 关于数据集的制作 (Issue #1) |

您好，感谢您的回复！我的qq是1432670918，不知道您是否方便添加好友？感谢您的帮助！


------------------&nbsp;原始邮件&nbsp;------------------
发件人: "learner-lu/image-super-resolution" ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [learner-lu/image-super-resolution] 关于数据集的制作 (Issue #1)






我研究一下，尽快给你答复

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
